### ISSUE TITLE
Many episodes are not included anywhere

### ISSUE THREAD

**Issue by bast** [coderefinery/hpc-containers#4]
I am not sure where they come from and what the history or intent was:
```
advanced_recipe.rst: WARNING: document isn't included in any toctree
apptainer_gpus.rst: WARNING: document isn't included in any toctree
conda.rst: WARNING: document isn't included in any toctree
debugging.rst: WARNING: document isn't included in any toctree
env_scripts.rst: WARNING: document isn't included in any toctree
inspecting.rst: WARNING: document isn't included in any toctree
instructor-guide.rst: WARNING: document isn't included in any toctree
mpi_demo.rst: WARNING: document isn't included in any toctree
networking.rst: WARNING: document isn't included in any toctree
overlay.rst: WARNING: document isn't included in any toctree
quick-reference.rst: WARNING: document isn't included in any toctree
readonlydirs.rst: WARNING: document isn't included in any toctree
resources.rst: WARNING: document isn't included in any toctree
storage.rst: WARNING: document isn't included in any toctree
template.rst: WARNING: document isn't included in any toctree
time_travel.rst: WARNING: document isn't included in any toctree
webapp.rst: WARNING: document isn't included in any toctree
workflow.rst: WARNING: document isn't included in any toctree
```

Do you know more @eglerean @simo-tuomisto ? Is this some left-over from somewhere else?

**Comment by eglerean** [comment]
Those were early drafts based on ideas we discussed with Maiken and Simo + chatGPT suggestions for possible exercises or demo we might have wanted to do. In practice some of those stand-alone demos are now in the materials, some never made it to the materials but maybe they also WILL never make it to the materials.

To sum up: it is enough to take notes if there is any idea for future exercises, demos that is currently missing and then just delete all those unreferrenced files.

**Comment by bast** [comment]
I will move all unused files into a separate folder and later we can still decide what to do with them.

**Comment by maikenp** [comment]
Closing this as the unused files are moved into separate folder.
