### ISSUE TITLE
Unsure how to find the image dependency

### ISSUE THREAD

**Issue by bast** [coderefinery/hpc-containers#9]
The episode about sharing says:
> We can trail though the Dockerfiles hopefully linked to via the image registry page and we find the following dependency.

It is not clear from the text and link how the dependency can be found.

**Comment by bast** [comment]
@maikenp

**Comment by maikenp** [comment]
I have tried to improve it! Hope it is better. I would really like to embed a screencapture showing how it can be done, but I do not think that our sphinx setup supports video embedding.

**Comment by bast** [comment]
It's clearer now. Closing. But just for reference it is possible to embed videos in Sphinx docs.
